name: eye_20_20
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <3.16.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  is_lock_screen2: ^2.0.1
  screen_state: ^3.0.1
  flutter_local_notifications: ^16.2.0
  flutter_desktop_sleep: ^0.0.2
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.2
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.0.0+2
  time_range_picker: ^2.2.0
  shared_preferences: ^2.0.15
  cron: ^0.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true


  assets:
    - assets/images/


